# Generated by Django 4.2 on 2023-04-20 19:01

from django.db import migrations

def add_services(apps, schema_editor):
    emergency_service = apps.get_model('core', 'EmergencyService')
    emergency_service.objects.create(title="Полиция", service_code='02', phone='02')
    emergency_service.objects.create(title="Скорая помощь", service_code='03', phone='03')
    emergency_service.objects.create(title="Пожарная", service_code='01', phone='01')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appeal_do_not_call_appeal_status_and_more'),
    ]

    operations = [
        migrations.RunPython(add_services)
    ]
