# Generated by Django 4.2 on 2023-04-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230420_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyservice',
            options={'ordering': ['service_code'], 'verbose_name': 'Экстренная служба', 'verbose_name_plural': 'Экстренные службы'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='number',
            field=models.PositiveIntegerField(db_index=True, editable=False, unique=True, verbose_name='Номер обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='victims_number',
            field=models.PositiveIntegerField(verbose_name='Число пострадавших'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='Номер телефона'),
        ),
    ]
