# Generated by Django 4.2 on 2023-04-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emergencyservice_options_alter_appeal_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='core.applicant'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='number',
            field=models.UUIDField(db_index=True, editable=False, unique=True, verbose_name='Номер обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Завершено', 'Завершено')], default='В работе', max_length=255, verbose_name='Статус обращения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default=('М', 'Мужской'), max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='health_status',
            field=models.CharField(blank=True, default='Практически здоров', help_text='Аллергоанамнез, хранические заболевания и т.п.', max_length=255, null=True, verbose_name='Описания состояния здоровья'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='service_code',
            field=models.CharField(max_length=255, verbose_name='Код службы'),
        ),
    ]
