# Generated by Django 4.2 on 2023-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appeal_applicant_alter_appeal_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='first name', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='last_name', max_length=255, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(default='middle_name', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
