# Generated by Django 4.2 on 2023-04-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_applicant_first_name_applicant_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['first_name'], 'verbose_name': 'Заявитель', 'verbose_name_plural': 'Заявители'},
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='full_name',
        ),
    ]
