# Generated by Django 4.2 on 2023-04-24 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_applicant_options_remove_applicant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Номер обращения'),
        ),
    ]
